authors:
  gekkotadev:
    name: gekkotadev (Jeremy)
    description: Programming, Game Design, Documentation
    avatar: https://avatars.githubusercontent.com/u/114091010
    url: https://github.com/gekkotadev
  lhelex:
    name: Lex (Alessandra)
    description: Art, Writing, Documentation
    avatar: https://avatars.githubusercontent.com/u/188201691
    url: https://github.com/lhelex
  myuserjdb01-gif:
    name: Joseph
    description: Programming, Documentation
    avatar: https://avatars.githubusercontent.com/u/258805153
    url: https://github.com/myuserjdb01-gif
