name: Reject Commit
on:
  push:

jobs:
  conventions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install pnpm
        uses: pnpm/setup@v2
        with:
          runtime: node@lts
      - name: Build Tasks
        run: pnpm -r build; pnpm i
      - name: Scan Folders
        run: pnpm actions scan

  revert:
    runs-on: ubuntu-latest
    needs: [conventions]
    if: ${{ failure() }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Fetch current and prior state
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Revert the commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Revert the commit that triggered this workflow
          git revert --no-edit ${{ github.sha }}
          
          # Push the reverted commit back to the main branch
          git push origin main
