## TODO
## - [ ] Create AppImage
name: Release
on:
  workflow_dispatch:
    inputs:
      game_title:
        type: string
        description: Game title.
        required: true

      cache_invalidate:
        type: boolean
        description: Rebuild cache from scratch.
        default: false

env:
  GODOT_VERSION: "4.7"
  PROJECT_PATH: godot
  WINEPREFIX: /tmp/.wine

jobs:
  ## https://github.com/nutti/blender-daily-build/blob/main/.github/workflows/blender-daily-build.yaml
  blender:
    name: Build Blender
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m')"
      - name: Cache Blender
        id: cache-blender
        uses: actions/cache@v6
        with:
          key: ${{ runner.os }}-${{ steps.date.outputs.date }}
          path: |
            release

      - name: Checkout Blender source code from Blender official repository
        if: inputs.cache_invalidate || steps.cache-blender.outputs.cache-hit != 'true'
        run: |
          mkdir -p blender-build
          cd blender-build
          git clone https://projects.blender.org/blender/blender.git
      - name: Setup Python
        if: inputs.cache_invalidate || steps.cache-blender.outputs.cache-hit != 'true'
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install initial packages
        if: inputs.cache_invalidate || steps.cache-blender.outputs.cache-hit != 'true'
        run: |
          sudo apt update
          sudo apt install git git-lfs
          # Blender is requiring gcc 14, while Ubuntu 24.04 runner has gcc 13.
          sudo apt install gcc-14 g++-14
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 100
      - name: Install basic building environment
        if: inputs.cache_invalidate || steps.cache-blender.outputs.cache-hit != 'true'
        run: |
          cd blender-build/blender
          ./build_files/linux/install_linux_packages.py
      - name: Download libraries
        if: inputs.cache_invalidate || steps.cache-blender.outputs.cache-hit != 'true'
        run: |
          cd blender-build/blender
          ./build_files/utils/make_update.py --use-linux-libraries
      - name: Build Blender
        if: inputs.cache_invalidate || steps.cache-blender.outputs.cache-hit != 'true'
        run: |
          cd blender-build/blender
          make update
          make
      - name: Test Blender Binary
        if: inputs.cache_invalidate || steps.cache-blender.outputs.cache-hit != 'true'
        run: |
          ./blender-build/build_linux/bin/blender --background --factory-startup -noaudio
      - name: Compress Blender for the artifacts
        if: inputs.cache_invalidate || steps.cache-blender.outputs.cache-hit != 'true'
        run: |
          mkdir release
          cp -r blender-build/build_linux/bin release/blender
          cd release
          tar Jcf blender.tar.xz blender
          rm -rf blender
      - name: Create MD5 checksum file
        if: inputs.cache_invalidate || steps.cache-blender.outputs.cache-hit != 'true'
        run: |
          cd release
          md5sum blender.tar.xz > blender.tar.xz.md5
      - name: Upload artifact 
        uses: actions/upload-artifact@v7
        with:
          name: blender
          path: "release"

  dependencies:
    ## ggg sync doesn't work on ubuntu-latest.
    runs-on: windows-latest
    steps:
      ## By default, Github Actions doesn't have access to the code base.
      ##
      ## By "checking it out" the job can receive a copy of the code base while
      ## it's busy doing it's thing. This tends to be why it's the first step
      ## when a job NEEDS the repository (which isn't all the time).
      - uses: actions/checkout@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      ## Have whatever's installed persist through workflow runs so it doesn't
      ## need to be reinstalled in the future. Cheaper and faster.
      - name: Cache packages
        id: cache-packages
        uses: actions/cache@v6
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/ggg.lock') }}
          path: |
            addons
      - name: Cache ggg
        id: cache-ggg
        uses: actions/cache@v6
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/ggg.toml') }}
          path: |
            ~\.cargo\bin

      - name: Install Godot Goodie Grabber
        if: inputs.cache_invalidate || steps.cache-ggg.outputs.cache-hit != 'true'
        run: irm https://github.com/godotneers/ggg/releases/latest/download/ggg-installer.ps1 | iex
      - name: Sync dependencies
        if: inputs.cache_invalidate || steps.cache-packages.outputs.cache-hit != 'true'
        run: ggg sync --force

      ## Artifacts are Github Actions' mechanism for uploading and downloading
      ## the results of jobs. Here we upload the installed addons as an artifact
      ## so that it may be used in building the game.
      - name: Upload dependencies
        uses: actions/upload-artifact@v7
        with:
          name: dependencies-artifact
          path: addons/

  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:mono-4.7
    needs: [blender, dependencies]  # dependencies-artifacts needed.
    strategy:
      fail-fast: true
      matrix:
        include:
          ## Linux support should be prioritized attributed to a combination of
          ## the Steam Deck's popularity and being a far less hostile Operating
          ## System both for developers and end-users.
          - export: Linux
            extension: x64
            godot_export: Linux x86_64
            output_directory: dist/linux_x64
            export_name: linux_x64

          ## Builds for Windows should be provided but have lesser priority
          - export: Windows
            extension: exe
            godot_export: Windows Desktop x86_64
            output_directory: dist/windows_x64
            export_name: windows_x64

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive

      ## The cost of having Blender support during development.
      - name: Install Blender
        uses: bradyajohnston/setup-blender@v5
        with:
          version: latest

      ## Yes, we use the C# enabled version of Godot.
      - name: Install dotNET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            10.0.x

      - name: Download dependencies
        uses: actions/download-artifact@v8
        with:
          name: dependencies-artifact
          path: addons/
      - name: Download Blender
        uses: actions/download-artifact@v8
        with:
          name: blender
          path: .blender/

      - name: Restore Godot editor cache
        uses: actions/cache@v6
        with:
          path: ${{ env.PROJECT_PATH }}/.godot/
          key: godot-editor-${{ env.GODOT_VERSION }}-${{ hashFiles(format('{0}/**/*.tscn', env.PROJECT_PATH), format('{0}/**/*.gd', env.PROJECT_PATH), format('{0}/**/*.import', env.PROJECT_PATH)) }}
          restore-keys: |
            godot-editor-${{ env.GODOT_VERSION }}-

      - name: Restore Godot export templates
        uses: actions/cache@v6
        with:
          path: ~/.local/share/godot/export_templates/
          key: godot-templates-${{ env.GODOT_VERSION }}
          restore-keys: |
            godot-templates-

      ## LFS = Large File Storage
      ##
      ## For assets. They tend to be large.
      - name: Ensure LFS objects are present
        working-directory: ${{ github.workspace }}
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git lfs install --local
          git lfs pull

      - name: Setup export template paths
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot || true
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono \
             ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono || true

      - name: Import project assets
        run: |
          godot --headless --import || true

      - name: Configure Godot Editor Settings for Headless Mode
        run: |
          mkdir -p ~/.config/godot
          cat <<EOF > ~/.config/godot/editor_settings-4.tres
          [gd_resource type="EditorSettings" format=3]

          [resource]
          filesystem/import/blender/blender_path = "${{ github.workspace }}/.blender"
          filesystem/import/blender/blender3_path = "${{ github.workspace }}/.blender"
          EOF

      - name: Export build
        run: |
          mkdir -v -p ${{ matrix.output_directory }}
          EXPORT_DIR="$(readlink -f build)"
          godot --headless --verbose --export-release "${{ matrix.godot_export }}" \
            "$EXPORT_DIR/${{ matrix.export_name }}/${{ inputs.game_title }}.${{ matrix.extension }}"

      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.export_name }}
          path: ${{ matrix.output_directory }}

  release:
    name: Release Distributables
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%d-%m')"
      - name: Get current time
        id: time
        run: echo "::set-output name=time::$(date + '%H:%M:%S')"
      
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get branch name
        id: get_branch
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Download Linux Artifact
        uses: actions/download-artifact@v5
        with:
          name: linux_x64
      
      - name: Download Windows Artifact
        uses: actions/download-artifact@v5
        with:
          name: windows_x64
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.date.outputs.date }}.${{ github.run_id }}
          release_name: Build ${{ steps.date.outputs.date }}.${{ github.run_id }}
          body: |
              Metadata        | Value 
              ----------------|---------------------------------------------------------------
              Build Timestamp | ${{ steps.date.outputs.date }} ${{ steps.date.outputs.time }} 
              Build ID        | `${{ steps.date.outputs.date }}.${{ github.run_id }}`

              ## Higlights! 🤩

              - …

              ## What's New? ✨📦

              - …

              ## What's Changed? 🔍

              - …

              ## Bug Fixes 🎶🎷🐛

              - …

          draft: true
          prerelease: true
    
      - name: Upload Linux Release Assets
        id: upload-linux-x64-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: linux_x64.zip
            asset_name: ${{ inputs.game_title }}-linux_x64.zip
            asset_content_type: application/zip
      
      - name: Upload Windows Release Assets
        id: upload-windows-x64-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: windows_x64.zip
            asset_name: ${{ inputs.game_title }}-windows_x64.zip
            asset_content_type: application/zip
