name: Replace Slurs
on: [push, pull_request]

jobs:
  replace:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Mate, you know who you are and why we're doing this. We really can't
        # let you sneak in slurs and controversial ideas within the codebase.
        include:
          - find: retardation
            replace: tarnation
            regex: false
          - find: retarded
            replace: silly
            regex: false
          - find: retard
            replace: goofball
            regex: false
          - find: trann
            replace: brand
            regex: false
          - find: fag
            replace: fly
            regex: false
          - find: dyk
            replace: tik
            regex: false
          - find: nigg
            replace: broth
            regex: false
          - find: Grok
            replace: Wik
            regex: false

          - find: "holier[ -]than[ -]thou"
            replace: \"I'm wrong\"
            regex: true

    steps:
      - uses: actions/checkout@v2
      - name: "Slur Replacement: ${{ matrix.replace }}"
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: ${{ matrix.find }}
          replace: ${{ matrix.replace }}
          include: "**/*.{cs,css,gd,js,json,md,py,rs,toml,tres,ts,tscn}"
          regex: ${{ matrix.regex }}
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
